import React, { useState } from "react";
import {
  BarChart3,
  TrendingUp,
  AlertOctagon,
  ShieldCheck,
  Download,
  Calendar,
  Layers,
  FileCheck2,
  PieChart,
  Radio,
  ExternalLink,
  ChevronRight,
  Filter,
  ArrowUpRight,
  Activity,
  X,
  BookOpen,
  Feather,
} from "lucide-react";
import { Header } from "../components/Header";
import { Footer } from "../components/Footer";
import { MethodologyModal } from "../components/MethodologyModal";
import { SubmitClaimModal } from "../components/SubmitClaimModal";
import { IntelligenceReport } from "../types";
import { CURATED_INTELLIGENCE_REPORTS } from "../data/reportsData";

export const Reports: React.FC = () => {
  const [reports] = useState<IntelligenceReport[]>(CURATED_INTELLIGENCE_REPORTS);
  const [activeReport, setActiveReport] = useState<IntelligenceReport>(
    CURATED_INTELLIGENCE_REPORTS[0]
  );
  const [isSubmitModalOpen, setIsSubmitModalOpen] = useState(false);
  const [isMethodologyOpen, setIsMethodologyOpen] = useState(false);
  const [showFullReportModal, setShowFullReportModal] = useState(false);

  const handleDownloadReport = (rep: IntelligenceReport) => {
    const text = `# FactLive Intelligence Report: ${rep.title}
Period: ${rep.period} | Published: ${rep.publishedDate}
Quarter: ${rep.quarter} ${rep.year}

## Executive Summary
${rep.summary}

## Key Intelligence Highlights
${rep.highlights.map((h) => `- ${h}`).join("\n")}

## Key Metrics
- Total Claims Audited: ${rep.keyMetrics.totalClaimsAudited.toLocaleString()}
- Falsehood & Distortion Rate: ${rep.keyMetrics.falsehoodPercentage}%
- Average Evidentiary Confidence: ${rep.keyMetrics.avgConfidence}%
- Primary Threat Topic: ${rep.keyMetrics.topCirculatingTopic}
- Velocity Risk Score: ${rep.keyMetrics.velocityRiskScore}/100

## Category Breakdown
${rep.categoryBreakdown.map((c) => `- **${c.category}**: ${c.total} total (${c.falseCount} false, ${c.misleadingCount} misleading, ${c.trueCount} verified true)`).join("\n")}

## Top Viral Debunks of the Period
${rep.topDebunks.map((d) => `### Claim: "${d.claim}"\n- Verdict: ${d.verdict}\n- Reach: ${d.reachEstimate}\n- Takeaway: ${d.keyTakeaway}\n`).join("\n")}

## Active Threat Vectors & Trajectory
${rep.threatVectors.map((v) => `- **${v.name}** [${v.riskLevel} - ${v.trend}]: ${v.description}`).join("\n")}

Generated by FactLive Intelligence. All data IFCN non-partisan audited.`;

    const blob = new Blob([text], { type: "text/markdown" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `FactLive-Intelligence-${rep.id}.md`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  return (
    <div className="min-h-screen bg-[#FBF9F5] dark:bg-[#121110] text-[#1C1917] dark:text-[#F5F2EB] flex flex-col font-serif transition-colors">
      <Header
        activeTab="verify"
        setActiveTab={() => {}}
        onOpenSubmitModal={() => setIsSubmitModalOpen(true)}
        onOpenMethodology={() => setIsMethodologyOpen(true)}
        totalVerifiedCount={142}
      />

      {/* Hero Header Masthead */}
      <section className="border-b-2 border-stone-800 dark:border-stone-700 bg-[#FAF7F2] dark:bg-[#181715] py-10 px-4 sm:px-6">
        <div className="mx-auto max-w-7xl">
          <div className="flex flex-col md:flex-row md:items-center justify-between gap-6">
            <div className="space-y-3 max-w-2xl">
              <div className="inline-flex items-center gap-2 border border-stone-800 dark:border-stone-300 bg-[#F4EFE6] dark:bg-[#22201D] px-3.5 py-1 text-xs font-mono font-bold tracking-widest text-stone-900 dark:text-stone-100 uppercase">
                <Feather className="h-3.5 w-3.5" />
                <span>QUARTERLY STATISTICAL GAZETTE & THREAT RADAR</span>
              </div>
              <h1 className="text-3xl sm:text-4xl lg:text-5xl font-black font-serif tracking-tight text-stone-900 dark:text-stone-100">
                Truth Intelligence & Trend Reports
              </h1>
              <p className="text-base sm:text-lg font-serif text-stone-700 dark:text-stone-300 leading-relaxed">
                Empirical audit data measuring rumor velocity, deepfake proliferation rates, and institutional falsehood distribution across hundreds of thousands of dispatches.
              </p>
            </div>

            {/* Select Report Quarter */}
            <div className="border border-stone-300 dark:border-stone-700 bg-white dark:bg-[#1A1817] p-3 shadow-sm space-y-2">
              <span className="text-xs font-mono font-bold text-stone-700 dark:text-stone-300 uppercase tracking-wider block">
                Audit Edition:
              </span>
              <div className="flex gap-1">
                {reports.map((rep) => (
                  <button
                    key={rep.id}
                    onClick={() => setActiveReport(rep)}
                    className={`px-3 py-1.5 text-xs font-mono uppercase tracking-wider transition-all cursor-pointer ${
                      activeReport.id === rep.id
                        ? "bg-stone-900 dark:bg-stone-100 text-stone-100 dark:text-stone-900 font-bold"
                        : "bg-[#F4EFE6] dark:bg-[#141312] text-stone-700 dark:text-stone-300 hover:bg-stone-200 dark:hover:bg-stone-800 border border-stone-300 dark:border-stone-800"
                    }`}
                  >
                    {rep.quarter} {rep.year}
                  </button>
                ))}
              </div>
            </div>
          </div>

          {/* High-Level KPI Matrix */}
          <div className="mt-8 grid grid-cols-2 lg:grid-cols-4 gap-3.5 border-y-2 border-stone-800 dark:border-stone-700 py-3 bg-white dark:bg-[#1A1817]">
            <div className="p-3 border-r border-stone-300 dark:border-stone-800 last:border-r-0">
              <div className="flex items-center justify-between text-xs font-mono text-stone-600 dark:text-stone-400 mb-1">
                <span className="uppercase tracking-wider font-bold">Claims Audited</span>
                <FileCheck2 className="h-3.5 w-3.5 text-stone-700 dark:text-stone-300" />
              </div>
              <div className="text-2xl sm:text-3xl font-bold font-serif text-stone-900 dark:text-stone-100">
                {activeReport.keyMetrics.totalClaimsAudited.toLocaleString()}
              </div>
              <div className="mt-1 text-[10px] text-stone-500 font-mono">+22% vs prior cycle</div>
            </div>

            <div className="p-3 border-r border-stone-300 dark:border-stone-800 last:border-r-0">
              <div className="flex items-center justify-between text-xs font-mono text-stone-600 dark:text-stone-400 mb-1">
                <span className="uppercase tracking-wider font-bold">Falsehood Rate</span>
                <AlertOctagon className="h-3.5 w-3.5 text-rose-700 dark:text-rose-400" />
              </div>
              <div className="text-2xl sm:text-3xl font-bold font-serif text-rose-800 dark:text-rose-400">
                {activeReport.keyMetrics.falsehoodPercentage}%
              </div>
              <div className="mt-1 text-[10px] text-stone-500 font-mono">Misleading or false</div>
            </div>

            <div className="p-3 border-r border-stone-300 dark:border-stone-800 last:border-r-0">
              <div className="flex items-center justify-between text-xs font-mono text-stone-600 dark:text-stone-400 mb-1">
                <span className="uppercase tracking-wider font-bold">Evidentiary Rigor</span>
                <ShieldCheck className="h-3.5 w-3.5 text-emerald-700 dark:text-emerald-400" />
              </div>
              <div className="text-2xl sm:text-3xl font-bold font-serif text-stone-900 dark:text-stone-100">
                {activeReport.keyMetrics.avgConfidence}%
              </div>
              <div className="mt-1 text-[10px] text-stone-500 font-mono">Cross-source consensus</div>
            </div>

            <div className="p-3">
              <div className="flex items-center justify-between text-xs font-mono text-stone-600 dark:text-stone-400 mb-1">
                <span className="uppercase tracking-wider font-bold">Velocity Risk</span>
                <Activity className="h-3.5 w-3.5 text-amber-700 dark:text-amber-400" />
              </div>
              <div className="text-2xl sm:text-3xl font-bold font-serif text-amber-800 dark:text-amber-400">
                {activeReport.keyMetrics.velocityRiskScore}/100
              </div>
              <div className="mt-1 text-[10px] text-stone-500 font-mono">Virality acceleration</div>
            </div>
          </div>
        </div>
      </section>

      {/* Main Content Area */}
      <main className="flex-1 mx-auto w-full max-w-7xl px-4 sm:px-6 py-8 space-y-8">
        {/* Active Report Header & Download */}
        <div className="border-2 border-stone-800 dark:border-stone-700 bg-white dark:bg-[#1A1817] p-6 sm:p-8 shadow-sm flex flex-col md:flex-row md:items-center justify-between gap-6">
          <div className="space-y-2 max-w-3xl">
            <div className="flex items-center gap-2">
              <span className="border border-stone-800 dark:border-stone-300 bg-stone-900 dark:bg-stone-100 px-2.5 py-0.5 font-mono text-xs font-bold text-stone-100 dark:text-stone-900 uppercase">
                {activeReport.quarter} {activeReport.year} Intel Briefing
              </span>
              <span className="text-xs text-stone-500 font-mono">
                Audit Period: {activeReport.period}
              </span>
            </div>
            <h2 className="text-2xl sm:text-3xl font-serif font-black text-stone-900 dark:text-stone-100 leading-tight">
              {activeReport.title}
            </h2>
            <p className="text-sm sm:text-base font-serif text-stone-700 dark:text-stone-300 leading-relaxed">
              {activeReport.summary}
            </p>
          </div>

          <div className="flex flex-wrap items-center gap-2 self-start md:self-auto">
            <button
              onClick={() => setShowFullReportModal(true)}
              className="border border-stone-300 dark:border-stone-700 bg-[#FAF7F2] dark:bg-[#141312] px-4 py-2.5 text-xs font-mono font-medium text-stone-800 dark:text-stone-200 hover:bg-stone-200 dark:hover:bg-stone-800 transition-colors cursor-pointer"
            >
              View Full Briefing
            </button>
            <button
              onClick={() => handleDownloadReport(activeReport)}
              className="flex items-center gap-1.5 bg-stone-900 dark:bg-stone-100 text-stone-100 dark:text-stone-900 border border-stone-900 dark:border-stone-100 px-4 py-2.5 text-xs font-mono font-bold uppercase tracking-wider transition-all cursor-pointer"
            >
              <Download className="h-4 w-4" />
              <span>Export Report (.md)</span>
            </button>
          </div>
        </div>

        {/* Category Breakdown Charts */}
        <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
          {/* Category Truth Breakdown Visualizer */}
          <div className="lg:col-span-2 border-2 border-stone-800 dark:border-stone-700 bg-white dark:bg-[#1A1817] p-6 sm:p-8 space-y-5 shadow-sm">
            <div className="flex flex-col sm:flex-row sm:items-center justify-between border-b border-stone-200 dark:border-stone-800 pb-3 gap-2">
              <div>
                <h3 className="text-lg font-serif font-bold text-stone-900 dark:text-stone-100">
                  Truth vs Falsehood by Beat & Subject Domain
                </h3>
                <p className="text-xs font-serif text-stone-600 dark:text-stone-400">
                  Distribution of audited dispatches across primary reporting desks
                </p>
              </div>
              <div className="flex items-center gap-3 text-[11px] font-mono font-bold">
                <span className="flex items-center gap-1 text-emerald-800 dark:text-emerald-300">
                  <span className="h-2.5 w-2.5 bg-emerald-700" /> True
                </span>
                <span className="flex items-center gap-1 text-amber-800 dark:text-amber-300">
                  <span className="h-2.5 w-2.5 bg-amber-600" /> Misleading
                </span>
                <span className="flex items-center gap-1 text-rose-800 dark:text-rose-300">
                  <span className="h-2.5 w-2.5 bg-rose-700" /> False
                </span>
              </div>
            </div>

            <div className="space-y-4">
              {activeReport.categoryBreakdown.map((cat, idx) => {
                const truePct = ((cat.trueCount / cat.total) * 100).toFixed(0);
                const misPct = ((cat.misleadingCount / cat.total) * 100).toFixed(0);
                const falsePct = ((cat.falseCount / cat.total) * 100).toFixed(0);

                return (
                  <div key={idx} className="space-y-1.5">
                    <div className="flex items-center justify-between text-xs">
                      <span className="font-serif font-bold text-stone-900 dark:text-stone-100">{cat.category}</span>
                      <span className="font-mono text-stone-600 dark:text-stone-400 text-[11px]">
                        {cat.total.toLocaleString()} claims ({falsePct}% False)
                      </span>
                    </div>

                    {/* Multi-Segment Proportion Bar */}
                    <div className="flex h-3.5 w-full border border-stone-400 dark:border-stone-700 bg-stone-200 dark:bg-stone-800 overflow-hidden">
                      <div
                        style={{ width: `${truePct}%` }}
                        className="bg-emerald-700 hover:opacity-90 transition-all"
                        title={`True: ${cat.trueCount} (${truePct}%)`}
                      />
                      <div
                        style={{ width: `${misPct}%` }}
                        className="bg-amber-600 hover:opacity-90 transition-all"
                        title={`Misleading: ${cat.misleadingCount} (${misPct}%)`}
                      />
                      <div
                        style={{ width: `${falsePct}%` }}
                        className="bg-rose-700 hover:opacity-90 transition-all"
                        title={`False: ${cat.falseCount} (${falsePct}%)`}
                      />
                    </div>
                  </div>
                );
              })}
            </div>
          </div>

          {/* Active Threat Vectors Column */}
          <div className="border-2 border-stone-800 dark:border-stone-700 bg-[#FAF7F2] dark:bg-[#181715] p-6 space-y-4 shadow-sm">
            <div className="border-b border-stone-300 dark:border-stone-800 pb-3">
              <h3 className="text-base font-serif font-bold text-stone-900 dark:text-stone-100">
                Disinformation Threat Vectors
              </h3>
              <p className="text-xs font-serif text-stone-600 dark:text-stone-400">
                Active amplification vectors & trajectory
              </p>
            </div>

            <div className="space-y-3">
              {activeReport.threatVectors.map((vector, idx) => (
                <div
                  key={idx}
                  className="border border-stone-300 dark:border-stone-800 bg-white dark:bg-[#141312] p-3.5 space-y-1.5"
                >
                  <div className="flex items-center justify-between">
                    <h4 className="text-xs font-serif font-bold text-stone-900 dark:text-stone-100">{vector.name}</h4>
                    <span
                      className={`border px-1.5 py-0.2 font-mono text-[10px] font-bold ${
                        vector.riskLevel === "Critical"
                          ? "border-rose-700 text-rose-800 dark:text-rose-300 bg-rose-50 dark:bg-rose-950"
                          : "border-amber-700 text-amber-800 dark:text-amber-300 bg-amber-50 dark:bg-amber-950"
                      }`}
                    >
                      {vector.riskLevel}
                    </span>
                  </div>
                  <div className="flex items-center gap-1.5 text-[11px] font-mono text-stone-700 dark:text-stone-300 font-bold">
                    <TrendingUp className="h-3 w-3" />
                    <span>Trend: {vector.trend}</span>
                  </div>
                  <p className="text-xs font-serif text-stone-700 dark:text-stone-300 leading-relaxed">{vector.description}</p>
                </div>
              ))}
            </div>
          </div>
        </div>

        {/* Top Viral Falsehoods of the Period */}
        <div className="border-2 border-stone-800 dark:border-stone-700 bg-white dark:bg-[#1A1817] p-6 sm:p-8 space-y-5 shadow-sm">
          <div className="border-b-2 border-stone-800 dark:border-stone-700 pb-3">
            <h3 className="text-lg font-serif font-bold text-stone-900 dark:text-stone-100">
              Top Circulating Rumors Audited During the Period
            </h3>
            <p className="text-xs font-serif text-stone-600 dark:text-stone-400">
              Highest-reach viral claims and official non-partisan evidentiary rulings
            </p>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
            {activeReport.topDebunks.map((debunk, idx) => (
              <div
                key={idx}
                className="border border-stone-300 dark:border-stone-800 bg-[#FAF7F2] dark:bg-[#141312] p-4 space-y-2.5 flex flex-col justify-between"
              >
                <div className="space-y-2">
                  <div className="flex items-center justify-between">
                    <span
                      className={`border px-2 py-0.5 font-mono text-[10px] font-bold ${
                        debunk.verdict === "FALSE"
                          ? "border-rose-700 text-rose-800 dark:text-rose-300 bg-rose-50 dark:bg-rose-950"
                          : "border-amber-700 text-amber-800 dark:text-amber-300 bg-amber-50 dark:bg-amber-950"
                      }`}
                    >
                      {debunk.verdict}
                    </span>
                    <span className="font-mono text-[10px] text-stone-500">
                      Circulation: {debunk.reachEstimate}
                    </span>
                  </div>
                  <h4 className="text-sm font-serif font-bold text-stone-900 dark:text-stone-100 leading-snug">
                    "{debunk.claim}"
                  </h4>
                </div>

                <div className="border border-stone-300 dark:border-stone-800 bg-white dark:bg-[#1A1817] p-2.5 text-xs font-serif text-stone-700 dark:text-stone-300">
                  <span className="font-bold text-stone-900 dark:text-stone-100 font-mono text-[11px] uppercase block mb-0.5">Ruling: </span>
                  {debunk.keyTakeaway}
                </div>
              </div>
            ))}
          </div>
        </div>
      </main>

      {/* Full Report Briefing Modal */}
      {showFullReportModal && (
        <div
          className="fixed inset-0 z-50 flex items-center justify-center bg-black/80 p-4 backdrop-blur-sm overflow-y-auto"
          onClick={() => setShowFullReportModal(false)}
        >
          <div
            className="relative w-full max-w-3xl my-8 border-2 border-stone-800 dark:border-stone-700 bg-[#FAF7F2] dark:bg-[#181715] p-6 sm:p-8 text-[#1C1917] dark:text-[#F5F2EB] shadow-2xl space-y-6"
            onClick={(e) => e.stopPropagation()}
          >
            <button
              onClick={() => setShowFullReportModal(false)}
              className="absolute right-4 top-4 border border-stone-800 bg-stone-900 text-stone-100 p-1.5 hover:bg-stone-800 transition-colors cursor-pointer"
            >
              <X className="h-5 w-5" />
            </button>

            <div className="border-b-2 border-stone-800 dark:border-stone-700 pb-4">
              <span className="border border-stone-800 dark:border-stone-300 bg-stone-900 dark:bg-stone-100 px-2.5 py-0.5 font-mono text-xs font-bold text-stone-100 dark:text-stone-900 uppercase">
                {activeReport.quarter} {activeReport.year} Full Dossier
              </span>
              <h2 className="text-2xl sm:text-3xl font-serif font-black text-stone-900 dark:text-stone-100 mt-2">{activeReport.title}</h2>
              <p className="text-xs text-stone-500 font-mono mt-1">Audit Period: {activeReport.period} | Published: {activeReport.publishedDate}</p>
            </div>

            <div className="space-y-4 text-sm font-serif text-stone-800 dark:text-stone-200 leading-relaxed">
              <h3 className="text-base font-serif font-bold text-stone-900 dark:text-stone-100">Executive Summary</h3>
              <p>{activeReport.summary}</p>

              <h3 className="text-base font-serif font-bold text-stone-900 dark:text-stone-100 pt-2">Key Highlights & Findings</h3>
              <ul className="space-y-2 list-disc pl-5 text-xs font-serif text-stone-800 dark:text-stone-200">
                {activeReport.highlights.map((h, i) => (
                  <li key={i}>{h}</li>
                ))}
              </ul>
            </div>

            <div className="flex items-center justify-end gap-2 border-t-2 border-stone-800 dark:border-stone-700 pt-4">
              <button
                onClick={() => handleDownloadReport(activeReport)}
                className="flex items-center gap-1.5 bg-stone-900 dark:bg-stone-100 text-stone-100 dark:text-stone-900 px-4 py-2 text-xs font-mono font-bold uppercase tracking-wider transition-colors cursor-pointer"
              >
                <Download className="h-4 w-4" />
                <span>Download Report (.md)</span>
              </button>
              <button
                onClick={() => setShowFullReportModal(false)}
                className="border border-stone-400 dark:border-stone-700 px-4 py-2 text-xs font-mono text-stone-700 dark:text-stone-300 hover:bg-stone-200 dark:hover:bg-stone-800 cursor-pointer"
              >
                Close
              </button>
            </div>
          </div>
        </div>
      )}

      <Footer
        onOpenMethodology={() => setIsMethodologyOpen(true)}
        onOpenSubmit={() => setIsSubmitModalOpen(true)}
      />

      <MethodologyModal
        isOpen={isMethodologyOpen}
        onClose={() => setIsMethodologyOpen(false)}
      />
      <SubmitClaimModal
        isOpen={isSubmitModalOpen}
        onClose={() => setIsSubmitModalOpen(false)}
      />
    </div>
  );
};
